
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/team03-s23-6pm-3
owner: ucsb-cs156-s23
repo_name: team03-s23-6pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjczNzY2Mzgx","is_bot":false,"login":"nhs-wobuzhidao","name":""},"headRefName":"movie-frontend","number":39,"title":"Movie frontend","url":"https://github.com/ucsb-cs156-s23/team03-s23-6pm-3/pull/39"},{"author":{"id":"MDQ6VXNlcjU2MDkyODkx","is_bot":false,"login":"Anshuman-UCSB","name":"Anshuman Dash"},"headRefName":"ad-song-frontend","number":38,"title":"Ad song frontend","url":"https://github.com/ucsb-cs156-s23/team03-s23-6pm-3/pull/38"}]
